name: Weekly Report - Scatter Diagram of Commits (lines added and files modified)

on:
  schedule:
    - cron: "59 23 * * 0" # Every Sunday at 23:59
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub matplotlib
      - name: Generate histogram with open issues
        run: python generate_weekly_histogram.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Generate histogram with closed issues
        run: python generate_weekly_histogram.py --state closed
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Upload Scatter Diagram commits
        uses: actions/upload-artifact@v2
        with:
          name: scatter_issues_commits
          path: scatter_issues_commits.png
